version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: |
              python -m venv venv
              source ./venv/bin/activate
              pip install pytest
              pip install flake8
              flake8 ./flaskr
  test:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: |
              python -m venv venv
              source ./venv/bin/activate
              pip install pytest
              pip install flask
              pytest --junit-xml=test-results/pytest.xml
              # テスト結果を保存する
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            sqlite3 flaskr.db < flaskr/schema.sql
            yum -y install git
            git add .
            git commit -m 'dbcreate'
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
